# Generated by Django 5.0.6 on 2024-06-28 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='code',
            new_name='dep_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='description',
            new_name='dep_description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='id',
            new_name='dep_id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dep_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='departmentCode',
            new_name='dep_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='address',
            new_name='emp_address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='age',
            new_name='emp_age',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birthdate',
            new_name='emp_birthdate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='code',
            new_name='emp_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='emp_email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='gender',
            new_name='emp_gender',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='marital_status',
            new_name='emp_marital_status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='emp_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nationality',
            new_name='emp_nationality',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone',
            new_name='emp_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='officeCode',
            new_name='off_code',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='departmentCode',
            new_name='dep_code',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='code',
            new_name='off_code',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='description',
            new_name='off_description',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='id',
            new_name='off_id',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='name',
            new_name='off_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
